export const SET_TRIPS = 'SET_TRIPS';
export const ADD_TRIP = 'ADD_TRIP';
export const MODIFY_TRIP = 'MODIFY_TRIP';
export const SELECT_TRIP = 'SELECT_TRIP';
export const DELETE_TRIP = 'DELETE_TRIP';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const MODIFY_CATEGORY = 'MODIFY_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const SET_TOTAL_AMOUNT = 'SET_TOTAL_AMOUNT';
export const LOAD_PAYMENTS = 'LOAD_PAYMENTS';
export const ADD_PAYMENT = 'ADD_PAYMENT';
export const MODIFY_PAYMENT = 'MODIFY_PAYMENT';
export const DELETE_PAYMENT = 'DELETE_PAYMENT';
